#' Reading a single FARS file
#'
#' This function takes one argument, \code{filename}, and, if the corresponding
#' file exists, reads it using the \code{read_csv} function from the
#' \code{readr} package, suppressing any messages (as well as progress
#' indication) generated by this function. The data in the file is then
#' converted to a tibble, using the \code{tbl_df} function from the
#'  \code{dplyr} package.
#'
#' @param filename A string indicating the name of the file to be read. This
#' may be an absolute or relative file path, as well as a short file name,
#' in which case the search for the file will occur in the current working
#' directory.
#'
#' @return The function returns a tibble containing the data in the file. If
#' the file indicated by \code{filename} doesn't exist, an error is generated.
#'
#' @importFrom readr read_csv
#' @importFrom dplyr tbl_df
#'
#' @examples
#' \dontrun{fars_read("mydata.csv")}
#' \dontrun{fars_read("C:/Users/JaneDoe/R/ExampleData/mydata.csv")}
#' \dontrun{fars_read("~/Examples/mydata.zip")}
#'
#' @export
fars_read <- function(filename) {
  if(!file.exists(filename))
    stop("file '", filename, "' does not exist")
  data <- suppressMessages({
    readr::read_csv(filename, progress = FALSE)
  })
  dplyr::tbl_df(data)
}


#' Building a FARS filename for a given year or set of years
#'
#' This function takes one argument, \code{year}, and generates a string with
#' the FARS filename corresponding to that year.
#'
#' @param year The year or years for which filenames should be built. May be
#' of class numeric or character.
#'
#' @return The function returns the FARS filename(s) built from \code{year}.
#'
#' @examples
#' make_filename(c(2014, 2015))
#' make_filename("2014")
#'
#' @export
make_filename <- function(year) {
  year <- as.integer(year)
  file <- sprintf("accident_%d.csv.bz2", year)
  system.file("extdata", file, package="fars")
}


#' Reading a set of FARS files referring to multiple years
#'
#' This function takes as argument a vector containing the years whose data
#' one wants to read and returns a list of tibbles, each consisting of two
#' columns, MONTH and year, containing the month (number) and year of each
#' accident reported in that year. The function uses the \code{mutate} and
#' \code{select} functions, as well as the \code{\%>\%} operator, all from
#' the \code{dplyr} package.
#'
#' @param years A numeric or character vector containing the years whose data
#' one wants to read.
#'
#' @return The function returns a list of tibbles, one per year. If a certain
#' year is not valid, a warning is generated and the list returned will
#' contain a value of \code{NULL} in the position corresponding to that year.
#'
#' @importFrom dplyr mutate select %>%
#'
#' @examples
#' fars_read_years(c(2013, 2014, 2015))
#' fars_read_years(c("2013", "2014", "2015"))
#' fars_read_years(2013)
#' fars_read_years("2014")
#'
#' @export
fars_read_years <- function(years) {
  lapply(years, function(year) {
    file <- make_filename(year)
    tryCatch({
      dat <- fars_read(file)
      dplyr::mutate_(dat, year =~ year) %>%
        dplyr::select_(.dots = c("MONTH", "year"))
    }, error = function(e) {
      warning("invalid year: ", year)
      return(NULL)
    })
  })
}


#' Summarizing accidents over multiple years
#'
#' This function takes as argument a vector \code{years} containing the years
#' whose data one wants to summarize and returns a tibble summarizing the
#' number of accidents in each month of each year. The function uses the
#' \code{bind_rows}, \code{group_by}, \code{summarize} and \code{\%>\%}
#' functions, all from the \code{dplyr} package. It also uses the \code{spread}
#' function from the \code{tidyr} package.
#'
#' @param years A numeric or character vector containing the years whose data
#' one wants to summarize.
#'
#' @return The function returns a tibble with a MONTH column plus one additional
#' column per (valid) year and one row per month. Each cell thus contains the
#' total number of accidents occured in the corresponding month and year. If a
#' certain year is not valid, a warning is generated (from inside the auxiliary
#' function \code{fars_read_years}) and no data from that year is included in
#' the returned tibble.
#'
#' @importFrom dplyr bind_rows group_by summarize %>%
#' @importFrom tidyr spread
#'
#' @examples
#' fars_summarize_years(c(2013, 2014, 2015))
#' fars_summarize_years(c("2013", "2014", "2015"))
#' fars_summarize_years(2013)
#' fars_summarize_years("2014")
#'
#' @export
fars_summarize_years <- function(years) {
  dat_list <- fars_read_years(years)
  dplyr::bind_rows(dat_list) %>%
    dplyr::group_by_(~year, ~MONTH) %>%
    dplyr::summarize_(n =~ n()) %>%
    tidyr::spread_(key_col = "year", value_col = "n")
}


#' Generating a map of accidents for a given state and year
#'
#' This function takes a \code{state.num} argument, indicating the numerical
#' code of a given state, and a \code{year} argument, indicating the year
#' whose data one wants to plot. It then reads in the corresponding FARS file
#' and generates a plot with accident locations in that year and state,
#' superimposed on a map of said state. \code{fars_map_state} uses the
#' \code{map} function from the \code{maps} package to draw state boundaries.
#' It also uses the \code{filter} function from the \code{dplyr} package and
#' the \code{points} function from the \code{graphics} package.
#'
#' @param state.num A numerical or character variable indicating the numerical
#' code of a given state in the U.S.. The coding used is available at
#' \url{https://crashstats.nhtsa.dot.gov/#/DocumentTypeList/6}.
#' @param year A numerical or character variable indicating the year whose data
#' one wants to plot.
#'
#' @return The function (invisibly) returns \code{NULL} and prints a map with
#' the locations of accidents in year \code{year} and state \code{state.num}
#' indicated by points drawn on a map of said state. An error is thrown if
#' either of the arguments is invalid. If there are no accidents reported for
#' state \code{state.num} in year \code{year}, a message is printed, the
#' function (invisibly) returns \code{NULL} and no plot is drawn.
#'
#' @importFrom dplyr filter
#' @importFrom maps map
#' @importFrom graphics points
#'
#' @note Some of the states in a FARS file may not be present in the database
#' used by the \code{map} function in the \code{maps} package, which uses the
#' \code{\link[maps]{state}} database, containing 48 states. For example,
#' accident locations for the state of Hawaii, with \code{state.num = 15}, cannot
#' be plotted and calling the function for this state will result in an error.
#'
#' @examples
#' fars_map_state(1, "2013")
#' fars_map_state("12", 2014)
#' \dontrun{fars_map_state(14, 2014)}
#' \dontrun{fars_map_state(15, 2014)}
#'
#' @export
fars_map_state <- function(state.num, year) {
  filename <- make_filename(year)
  data <- fars_read(filename)
  state.num <- as.integer(state.num)

  if(!(state.num %in% unique(data$STATE)))
    stop("invalid STATE number: ", state.num)
  data.sub <- dplyr::filter_(data, ~ STATE == state.num)
  if(nrow(data.sub) == 0L) {
    message("no accidents to plot")
    return(invisible(NULL))
  }
  is.na(data.sub$LONGITUD) <- data.sub$LONGITUD > 900
  is.na(data.sub$LATITUDE) <- data.sub$LATITUDE > 90
  with(data.sub, {
    maps::map("state", ylim = range(LATITUDE, na.rm = TRUE),
              xlim = range(LONGITUD, na.rm = TRUE))
    graphics::points(LONGITUD, LATITUDE, pch = 46)
  })
}

